name: "Restore installed packages"

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'

    - name: Restore installed packages
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node_modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
