name: Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Package
        uses: ./.github/actions/install-packages
  
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore installed packages
        uses: ./.github/actions/restore-packages

      - name: Build storybook
        run: npm run build-storybook

      - name: Upload Documents
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
