name: pull request ci

on:
  pull_request:


defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Package
        uses: ./.github/actions/install-packages

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore installed packages
        uses: ./.github/actions/restore-packages

      - name: Run build
        run: npm run build

  eslint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore installed packages
        uses: ./.github/actions/restore-packages

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run ESLint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
